/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.tab-content[_ngcontent-%COMP%] {\r\n  padding: 20px;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovY3lnd2luNjQvaG9tZS9yZW1pLm1pY2hlbC93b3Jrc3BhY2UvYW5ndWxhci0yLXBvYy1kcmFnL3NyYy9hcHAvbWFpbi9tYWluLmNvbXBvbmVudC5zY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L2N5Z3dpbjY0L2hvbWUvcmVtaS5taWNoZWwvd29ya3NwYWNlL2FuZ3VsYXItMi1wb2MtZHJhZy9zcmMvYXBwL21haW4vbWFpbi5jb21wb25lbnQuc2NzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
