/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.split-container[_ngcontent-%COMP%]{\r\n  height: 300px;\r\n\r\n  split-area {\r\n    border: 1px solid gray;\r\n    padding: 10px;\r\n  }\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovY3lnd2luNjQvaG9tZS9yZW1pLm1pY2hlbC93b3Jrc3BhY2UvYW5ndWxhci0yLXBvYy1kcmFnL3NyYy9hcHAvcG9jLWFuZ3VsYXItc3BsaXQvcG9jLWFuZ3VsYXItc3BsaXQuY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovY3lnd2luNjQvaG9tZS9yZW1pLm1pY2hlbC93b3Jrc3BhY2UvYW5ndWxhci0yLXBvYy1kcmFnL3NyYy9hcHAvcG9jLWFuZ3VsYXItc3BsaXQvcG9jLWFuZ3VsYXItc3BsaXQuY29tcG9uZW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
