/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './main/main.component.ngfactory';
import * as i3 from './main/main.component';
import * as i4 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),4,'div',[['class','container-fluid']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-main',([] as any[]),(null as any),
          (null as any),(null as any),i2.View_MainComponent_0,i2.RenderType_MainComponent)),
      i1.ɵdid(49152,(null as any),0,i3.MainComponent,([] as any[]),(null as any),(null as any)),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n']))],
      (null as any),(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i4.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i4.AppComponent> = i1.ɵccf('app-root',
    i4.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovY3lnd2luNjQvaG9tZS9yZW1pLm1pY2hlbC93b3Jrc3BhY2UvYW5ndWxhci0yLXBvYy1kcmFnL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9jeWd3aW42NC9ob21lL3JlbWkubWljaGVsL3dvcmtzcGFjZS9hbmd1bGFyLTItcG9jLWRyYWcvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovY3lnd2luNjQvaG9tZS9yZW1pLm1pY2hlbC93b3Jrc3BhY2UvYW5ndWxhci0yLXBvYy1kcmFnL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovY3lnd2luNjQvaG9tZS9yZW1pLm1pY2hlbC93b3Jrc3BhY2UvYW5ndWxhci0yLXBvYy1kcmFnL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8IS0tVGhlIGNvbnRlbnQgYmVsb3cgaXMgb25seSBhIHBsYWNlaG9sZGVyIGFuZCBjYW4gYmUgcmVwbGFjZWQuLS0+XHJcbjxkaXYgY2xhc3M9XCJjb250YWluZXItZmx1aWRcIj5cclxuICA8YXBwLW1haW4+PC9hcHAtbWFpbj5cclxuPC9kaXY+XHJcbiIsIjxhcHAtcm9vdD48L2FwcC1yb290PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0FtRSx1Q0FDbkU7TUFBQTtNQUFBLDRDQUE2QjtNQUMzQjtVQUFBO2FBQUE7TUFBcUIsdUNBQ2pCOzs7O29CQ0hOO01BQUE7YUFBQTs7OzsifQ==
