/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from '../../node_modules/ngx-bootstrap/dropdown/bs-dropdown-container.component.ngfactory';
import * as i4 from './app.component.ngfactory';
import * as i5 from '@angular/common';
import * as i6 from '@angular/platform-browser';
import * as i7 from '@angular/animations/browser';
import * as i8 from '@angular/platform-browser/animations';
import * as i9 from '@angular/animations';
import * as i10 from '@angular/forms';
import * as i11 from 'ng2-dragula/components/dragula.provider';
import * as i12 from 'angular-tree-component/dist/models/tree-dragged-element.model';
import * as i13 from 'ngx-bootstrap/accordion/accordion.config';
import * as i14 from 'ngx-bootstrap/tabs/tabset.config';
import * as i15 from 'ngx-bootstrap/positioning/positioning.service';
import * as i16 from 'ngx-bootstrap/component-loader/component-loader.factory';
import * as i17 from 'ngx-bootstrap/dropdown/bs-dropdown.state';
import * as i18 from 'ngx-bootstrap/collapse/collapse.module';
import * as i19 from 'ngx-bootstrap/accordion/accordion.module';
import * as i20 from 'ngx-bootstrap/tabs/tabs.module';
import * as i21 from 'ng2-dragula/components/dragular.module';
import * as i22 from 'mobx-angular/dist/mobx-angular';
import * as i23 from 'angular-tree-component/dist/angular-tree-component';
import * as i24 from 'angular2-focus/src/focus.module';
import * as i25 from 'angular-split/dist/angularSplit.module';
import * as i26 from 'ngx-bootstrap/dropdown/bs-dropdown.module';
import * as i27 from 'ngx-bootstrap/dropdown/bs-dropdown.config';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.BsDropdownContainerComponentNgFactory,i4.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4352,i0.LOCALE_ID,
          'fr',([] as any[])),i0.ɵmpd(4608,i5.NgLocalization,i5.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(5120,
          i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i6.DomSanitizer,
              i6.ɵe,[i5.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i6.DomSanitizer]),
          i0.ɵmpd(4608,i6.HAMMER_GESTURE_CONFIG,i6.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i6.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i6.ɵDomEventsPlugin(p0_0),new i6.ɵKeyEventsPlugin(p1_0),new i6.ɵHammerGesturesPlugin(p2_0,
                p2_1)];
          },[i5.DOCUMENT,i5.DOCUMENT,i5.DOCUMENT,i6.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i6.EventManager,i6.EventManager,[i6.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i6.ɵDomSharedStylesHost,i6.ɵDomSharedStylesHost,[i5.DOCUMENT]),
          i0.ɵmpd(4608,i6.ɵDomRendererFactory2,i6.ɵDomRendererFactory2,[i6.EventManager,
              i6.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i7.AnimationDriver,i8.ɵc,([] as any[])),
          i0.ɵmpd(5120,i7.ɵAnimationStyleNormalizer,i8.ɵd,([] as any[])),i0.ɵmpd(4608,
              i7.ɵAnimationEngine,i8.ɵb,[i7.AnimationDriver,i7.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i8.ɵe,[i6.ɵDomRendererFactory2,i7.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(6144,i6.ɵSharedStylesHost,(null as any),[i6.ɵDomSharedStylesHost]),
          i0.ɵmpd(4608,i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i6.Meta,
              i6.Meta,[i5.DOCUMENT]),i0.ɵmpd(4608,i6.Title,i6.Title,[i5.DOCUMENT]),
          i0.ɵmpd(4608,i9.AnimationBuilder,i8.ɵBrowserAnimationBuilder,[i0.RendererFactory2]),
          i0.ɵmpd(4608,i10.ɵi,i10.ɵi,([] as any[])),i0.ɵmpd(4608,i11.DragulaService,
              i11.DragulaService,([] as any[])),i0.ɵmpd(4608,i12.TreeDraggedElement,
              i12.TreeDraggedElement,([] as any[])),i0.ɵmpd(4608,i13.AccordionConfig,
              i13.AccordionConfig,([] as any[])),i0.ɵmpd(4608,i14.TabsetConfig,i14.TabsetConfig,
              ([] as any[])),i0.ɵmpd(4608,i15.PositioningService,i15.PositioningService,
              ([] as any[])),i0.ɵmpd(4608,i16.ComponentLoaderFactory,i16.ComponentLoaderFactory,
              [i0.ComponentFactoryResolver,i0.NgZone,i0.Injector,i15.PositioningService,
                  i0.ApplicationRef]),i0.ɵmpd(4608,i17.BsDropdownState,i17.BsDropdownState,
              ([] as any[])),i0.ɵmpd(512,i5.CommonModule,i5.CommonModule,([] as any[])),
          i0.ɵmpd(1024,i0.ErrorHandler,i6.ɵa,([] as any[])),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any) => {
                return [i6.ɵc(p0_0,p0_1)];
              },[[2,i6.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i6.BrowserModule,i6.BrowserModule,[[3,i6.BrowserModule]]),i0.ɵmpd(512,
              i8.BrowserAnimationsModule,i8.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i10.ɵba,i10.ɵba,([] as any[])),i0.ɵmpd(512,i10.FormsModule,i10.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i18.CollapseModule,i18.CollapseModule,([] as any[])),
          i0.ɵmpd(512,i19.AccordionModule,i19.AccordionModule,([] as any[])),i0.ɵmpd(512,
              i20.TabsModule,i20.TabsModule,([] as any[])),i0.ɵmpd(512,i21.DragulaModule,
              i21.DragulaModule,([] as any[])),i0.ɵmpd(512,i22.MobxAngularModule,i22.MobxAngularModule,
              ([] as any[])),i0.ɵmpd(512,i23.TreeModule,i23.TreeModule,([] as any[])),
          i0.ɵmpd(512,i24.FocusModule,i24.FocusModule,([] as any[])),i0.ɵmpd(512,i25.AngularSplitModule,
              i25.AngularSplitModule,([] as any[])),i0.ɵmpd(512,i26.BsDropdownModule,
              i26.BsDropdownModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,i1.AppModule,
              ([] as any[])),i0.ɵmpd(256,i27.BsDropdownConfig,{autoClose:true},([] as any[])),
          i0.ɵmpd(256,i0.TRANSLATIONS_FORMAT,'xlf',([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovY3lnd2luNjQvaG9tZS9yZW1pLm1pY2hlbC93b3Jrc3BhY2UvYW5ndWxhci0yLXBvYy1kcmFnL3NyYy9hcHAvYXBwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9jeWd3aW42NC9ob21lL3JlbWkubWljaGVsL3dvcmtzcGFjZS9hbmd1bGFyLTItcG9jLWRyYWcvc3JjL2FwcC9hcHAubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
