/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './poc-i18n.component.scss.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './poc-i18n.component';
const styles_PocI18nComponent:any[] = [i0.styles];
export const RenderType_PocI18nComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PocI18nComponent,data:{}});
export function View_PocI18nComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Bonjour, comment ça va'])),(_l()(),i1.ɵted((null as any),
      ['\n\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['Bonjour avec une description à l\'intérieur de l\'attribut i18n'])),
      (_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['Bonjour, avec une description et un contexte à l\'intérieur de l\'attribut i18n'])),
      (_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['C\'est le titre principal avec un identifiant personnalisé'])),
      (_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          0,'img',[['src',''],['title','un titre d\'image en utilisant un i18n-title attribut']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n\n'])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'span',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['test'])),(_l()(),i1.ɵted((null as any),
          ['\n']))],(null as any),(null as any));
}
export function View_PocI18nComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-poc-i18n',
      ([] as any[]),(null as any),(null as any),(null as any),View_PocI18nComponent_0,
      RenderType_PocI18nComponent)),i1.ɵdid(114688,(null as any),0,i2.PocI18nComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const PocI18nComponentNgFactory:i1.ComponentFactory<i2.PocI18nComponent> = i1.ɵccf('app-poc-i18n',
    i2.PocI18nComponent,View_PocI18nComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovY3lnd2luNjQvaG9tZS9yZW1pLm1pY2hlbC93b3Jrc3BhY2UvYW5ndWxhci0yLXBvYy1kcmFnL3NyYy9hcHAvcG9jLWkxOG4vcG9jLWkxOG4uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L2N5Z3dpbjY0L2hvbWUvcmVtaS5taWNoZWwvd29ya3NwYWNlL2FuZ3VsYXItMi1wb2MtZHJhZy9zcmMvYXBwL3BvYy1pMThuL3BvYy1pMThuLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L2N5Z3dpbjY0L2hvbWUvcmVtaS5taWNoZWwvd29ya3NwYWNlL2FuZ3VsYXItMi1wb2MtZHJhZy9zcmMvYXBwL3BvYy1pMThuL3BvYy1pMThuLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovY3lnd2luNjQvaG9tZS9yZW1pLm1pY2hlbC93b3Jrc3BhY2UvYW5ndWxhci0yLXBvYy1kcmFnL3NyYy9hcHAvcG9jLWkxOG4vcG9jLWkxOG4uY29tcG9uZW50LnRzLlBvY0kxOG5Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cCBpMThuPlxuICBIZWxsbywgaG93IGFyZSB5b3UgP1xuPC9wPlxuXG48cCBpMThuPVwidGhpcyBpcyBhIHNtYWxsIGRlc2NyaXB0aW9uXCI+XG4gIEhlbGxvLCB3aXRoIGEgZGVzY3JpcHRpb24gaW5zaWRlIHRoZSBpMThuIGF0dHJpYnV0ZSA/XG48L3A+XG5cbjxoMSBpMThuPVwiaGVhZGVyIGNvbnRlbnR8dGhpcyBpcyBhIHNtYWxsIGRlc2NyaXB0aW9uXCI+XG4gIEhlbGxvLCB3aXRoIGEgZGVzY3JpcHRpb24gYW5kIHRoZSBjb250ZXh0IGluc2lkZSB0aGUgaTE4biBhdHRyaWJ1dGUgP1xuPC9oMT5cblxuPGgxIGkxOG49XCJAQHRpdGxlXCI+XG4gIFRoaXMgaXMgdGhlIG1haW4gdGl0bGUgd2l0aCBjdXN0b20gaWRcbjwvaDE+XG5cbjxpbWcgdGl0bGU9XCJpbWFnZSB0aXRsZSB3aXRoIGkxOG4tdGl0bGUgYXR0cmlidXRlXCIgaTE4bi10aXRsZSBzcmM9XCJcIiAvPlxuXG48c3BhbiBpMThuPlxuICB7dGVzdCwgcGx1cmFsLCA9MCB7bm8gdGVzdH0gPTEge29uZSB0ZXN0fSA9MiB7dHdvIHRlc3RzfSBvdGhlciB7bWFueSB0ZXN0c319XG48L3NwYW4+XG4iLCI8YXBwLXBvYy1pMThuPjwvYXBwLXBvYy1pMThuPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNBQTtNQUFBLHdFQUFBO2FBQUEsNENBRUk7TUFBQSxXQUVKO01BQUEsd0VBSkE7YUFBQTtNQU1JLHlDQUVKO1VBQUE7VUFBQSxnQkFSQTtNQVVLLHlDQUVMO1VBQUE7VUFBQSxnQkFaQTtNQWNLLHlDQUVMO1VBQUE7VUFBQTtNQUF1RSx5Q0FFdkU7VUFBQTtVQUFBLGdCQWxCQSx5Q0FvQk87VUFBQTs7O29CQ3BCUDtNQUFBO2lDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
