/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovY3lnd2luNjQvaG9tZS9yZW1pLm1pY2hlbC93b3Jrc3BhY2UvYW5ndWxhci0yLXBvYy1kcmFnL3NyYy9hcHAvcG9jLWkxOG4vcG9jLWkxOG4uY29tcG9uZW50LnNjc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovY3lnd2luNjQvaG9tZS9yZW1pLm1pY2hlbC93b3Jrc3BhY2UvYW5ndWxhci0yLXBvYy1kcmFnL3NyYy9hcHAvcG9jLWkxOG4vcG9jLWkxOG4uY29tcG9uZW50LnNjc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
